// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input 10x20.png --format mono2`

#pragma once

#include <qp.h>

extern const uint32_t font_10x20_length;
extern const uint8_t  font_10x20[2079];
